highlighter: pygment
markdown: kramdown
future: false

# Enable sass
sass:
    style: compressed
 
languages:          ['it']
language_default:   'it'

default_locale: "it" 

# site Name
name: "Undercustodian"

collections:
  home:
    output: true
    sort_by: index

